---
apiVersion: v1
# FIXME: turn into ReplicationController
kind: Pod
metadata:
  name: webconsole-api
  labels:
    app: webconsole-api
spec:
  # FIXME: drop this for production
  restartPolicy: Never
  serviceAccountName: deployer
  containers:
    - name: front-end
      # FIXME: hardcoded "cockpit-dev" project name
      image: image-registry.openshift-image-registry.svc:5000/cockpit-dev/webconsoleapp:latest
      #command: ["sleep", "infinity"]
      env:
        - name: API_URL
          value: https://test.cloud.redhat.com
        - name: SESSION_INSTANCE_DOMAIN
          value: .webconsoleapp-sessions.cockpit-dev.svc.cluster.local
      ports:
        - containerPort: 8080
          name: api

---
apiVersion: v1
# FIXME: turn into ReplicationController
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: docker.io/redis
      ports:
        - containerPort: 6379
          protocol: TCP
          name: redis

---
apiVersion: v1
kind: Service
metadata:
  name: webconsole
spec:
  ports:
  - name: api
    targetPort: 8080
    port: 8080
    protocol: TCP
  selector:
    app: webconsole-api

---
# headless Service for session pod DNS
apiVersion: v1
kind: Service
metadata:
  name: webconsoleapp-sessions
spec:
  clusterIP: None
  ports:
  # unused, but must have one formally
  - name: dummy
    targetPort: 1234
    port: 1234
  selector:
    app: webconsoleapp-session

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - name: redis
    targetPort: 6379
    port: 6379
    protocol: TCP
  selector:
    app: redis
