---

apiVersion: v1
kind: Pod

metadata:
  name: webconsoleapp
  labels:
    app: multiplexer

spec:
  restartPolicy: Never
  containers:
    - name: front-end
      image: localhost/webconsoleapp:latest
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - mountPath: /run/podman/podman.sock
          name: podman-socket
        - mountPath: /usr/local/bin/multiplexer.py
          name: multiplexer.py
          readOnly: true

    - name: redis
      image: docker.io/redis:latest

    - name: 3scale
      image: docker.io/library/nginx
      ports:
        - containerPort: 443
          hostPort: 8443
      volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: 3scale-nginx.conf
        - mountPath: /etc/nginx/certs/
          name: 3scale-certs
        - mountPath: /etc/nginx/.htpasswd
          name: 3scale-htpasswd

  volumes:
    - name: podman-socket
      hostPath:
        path: XDG_RUNTIME_DIR/podman/podman.sock

    - name: multiplexer.py
      hostPath:
        path: ./appservice/multiplexer.py

    - name: 3scale-nginx.conf
      hostPath:
        path: ./3scale/nginx.conf

    - name: 3scale-certs
      hostPath:
        path: ./3scale/certs/

    - name: 3scale-htpasswd
      hostPath:
        path: ./3scale/htpasswd
