---

apiVersion: v1
kind: Pod

metadata:
  name: webconsoleapp
  labels:
    app: multiplexer

spec:
  containers:
    - name: front-end
      image: localhost/webconsoleapp:latest
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - mountPath: /run/podman/podman.sock
          name: podman-socket
        - mountPath: /usr/local/bin/multiplexer.py
          name: multiplexer.py
          readOnly: true

    - name: redis
      image: docker.io/redis:latest

  volumes:
    - name: podman-socket
      hostPath:
        path: XDG_RUNTIME_DIR/podman/podman.sock

    - name: multiplexer.py
      hostPath:
        path: ./appservice/multiplexer.py

---

apiVersion: v1
kind: Pod

metadata:
  name: 3scale
  labels:
    app: 3scale

spec:
  containers:
    - name: nginx
      image: localhost/3scale:latest
      ports:
        - containerPort: 443
          hostPort: 8443
