---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: webconsoleapp

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: build-webconsoleapp
spec:
  source:
    type: Git
    git:
      uri: https://github.com/cockpit-project/console.dot
      # you can build from a proposed branch for testing with
      # ref: branchname
    contextDir: appservice
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: webconsoleapp:latest
