---

apiVersion: v1
kind: Pod

metadata:
  name: webconsoleapp
  labels:
    app: multiplexer

spec:
  restartPolicy: Never
  containers:
    - name: front-end
      image: localhost/webconsoleapp
      #command: ["sleep", "infinity"]
      ports:
        - containerPort: 8080
          hostPort: 8080
      volumeMounts:
        - mountPath: /run/podman/podman.sock
          name: podman-socket
        - mountPath: /usr/local/bin/
          name: appservice-mod
          readOnly: true
      env:
        # k8s compatible
        - name: REDIS_SERVICE_HOST
          # HACK: podman < 4 cannot DNS-resolve container names in pod, so use pod name
          # value: "webconsoleapp-redis"
          value: "webconsoleapp"
        - name: API_URL
          value: https://localhost:{PORT_3SCALE}
        - name: SESSION_INSTANCE_DOMAIN
          value: .dns.podman

    - name: redis
      image: docker.io/redis

    - name: 3scale
      image: docker.io/library/nginx
      ports:
        - containerPort: 443
          hostPort: {PORT_3SCALE}
      volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: 3scale-nginx.conf
        - mountPath: /etc/nginx/certs/
          name: 3scale-certs
        - mountPath: /etc/nginx/.htpasswd
          name: 3scale-htpasswd

  volumes:
    - name: podman-socket
      hostPath:
        path: {XDG_RUNTIME_DIR}/podman/podman.sock

    - name: appservice-mod
      hostPath:
        path: ./appservice/

    - name: 3scale-nginx.conf
      hostPath:
        path: ./3scale/nginx.conf

    - name: 3scale-certs
      hostPath:
        path: ./3scale/certs/

    - name: 3scale-htpasswd
      hostPath:
        path: ./3scale/htpasswd
