FROM debian:bookworm

RUN apt-get update && \
    apt-get install -y cockpit-bridge cockpit-system curl procps && \
    apt-get clean

RUN curl -L -o /usr/local/bin/websocat https://github.com/vi/websocat/releases/download/v1.10.0/websocat.x86_64-unknown-linux-musl && \
    chmod a+x /usr/local/bin/websocat
