# Test container image that represents a remote managed server which connects
# to consoledot. This illustrates the minimum dependencies.
FROM debian:bookworm

RUN apt-get update && \
    apt-get install -y cockpit-bridge cockpit-system ca-certificates python3 && \
    apt-get clean
