# Test container image that represents a remote managed server which connects
# to consoledot. This illustrates the minimum dependencies.

ARG tag
FROM quay.io/centos/centos:$tag

RUN dnf install -y cockpit-system python3 && dnf clean all
