FROM docker.io/redhat/ubi9-minimal

# iputils and procps-ng are just for debugging; drop for production
RUN microdnf install -y python3-pip iputils procps-ng && microdnf clean all
RUN pip3 install aiohttp redis

COPY *.py /usr/local/bin/

CMD python3 /usr/local/bin/multiplexer.py
