name: ci
on: [pull_request]
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sscg flake8

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Build containers and credentials
        run: make

      - name: Run integration test
        run: make check

      - name: flake8
        run: flake8
